version: '3.9'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://dietask:dietask@db:5432/dietask
    volumes:
      - ./backend:/app            # <— monta seu código dentro do container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: dietask
      POSTGRES_PASSWORD: dietask
      POSTGRES_DB: dietask
    ports:
      - "5432:5432"

